services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb-container
    environment:
      MARIADB_DATABASE: sistema
      MARIADB_USER: usuario1
      MARIADB_PASSWORD: pass.55
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./sistema.sql:/docker-entrypoint-initdb.d/sistema.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  php-apache:
    build: .
    container_name: php-apache-container
    volumes:
      - .:/var/www/html
    ports:
      - "86:80"
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
